### ISSUE TITLE
[Bug]: Consumables Reset Saturation

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/prorpgitems#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Consumables that do not have saturation stated clear players saturation.
Not sure if it happens to consumables that do have it do the same.

### Expected Behavior

For consumables to not "set" the players saturation and to just "add"
the number to existing saturation

### Environment

```markdown
-
```

**Comment by Travja** [comment]
Jamm, the code for this is a little interesting. It appears that the saturation is set based on the food level of the player and the saturation of the consumable. The problem is, this appears to be backwards.  Based on the below snippet, it appears that the saturation is actually set backwards(?) what it should be.

```java
            double max = EntityStats.getEntityMaxHealth(p);
            int food = (int) Math.min(20.0D, p.getFoodLevel() + getHunger());
            int saturation = 20 - food;
            p.setHealth(Math.min(p.getHealth() + getHealth(), max));
            p.setFoodLevel(food);
            p.setSaturation(saturation);
```

I'll modify this as requested to add the `effects.hunger` attribute from configuration to the _current_ saturation value because that makes sense to me as opposed to what this is currently doing.
