### ISSUE TITLE
[Bug]: Party module

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/prorpgitems#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Server crashes when I kill a mob while in a party with someone

### Expected Behavior

to not crash

### Steps To Reproduce

create a prorpgitems party
another player joins the party
kill a mob (that is not from spawn egg)

might be related to exp share since it didnt crash from spawn egg mobs which dont give exp

### Environment

```markdown
- Server Software: paper 1.17.1 328
- ProRPGItems Version: 1.0.3.11 (and 1.0.3.8)
- ProMCCore Version: 1.0.3.5
```

### latest.log

[21:41:11 INFO]: lordsrubka5 issued server command: /party create
[21:41:15 INFO]: lordsrubka5 issued server command: /party invite lordsrubka6
[21:41:20 INFO]: lordsrubka6 issued server command: /party join lordsrubka5
[21:41:24 INFO]: lordsrubka5 issued server command: /summon minecraft:zombie
[21:41:24 INFO]: [lordsrubka5: Summoned new Zombie]
[21:41:30 INFO]: Stopping server

**Comment by Travja** [comment]
Do you have any sort of crash report/stack trace from the crash? Or does it just stop the server without anything else to note?

**Comment by lordsrubka5** [comment]
Server console doesn't say anything other than stopping server. If you want me to check other places you have to tell me how to check them

**Comment by Travja** [comment]
Often, when a server crashes, it'll create a `crash_reports` directory in the server root that might have useful information. The latest.log can also contain some information that you might not otherwise see on the console before the server shuts down.

**Comment by lordsrubka5** [comment]
Crash report is empty and it didn't show anything in the latest.log other than stopping the server and all the plugins shutting down

**Comment by Travja** [comment]
This sure makes it hard to track down. Guess I'll have to get a set up going with parties and everything and see if I can make a server crash.

**Comment by lordsrubka5** [comment]
It doesn't break when I'm alone in the party and I kill a mob, it is most likely connected to the exp share

**Comment by redkk0523** [comment]
i agree it lags when the party module floods exp msg i do /tps to check if tps was affected and it did not, in my case it doesnt crash the server, if maybe when someone kills a mob while in a party to like total the exp shared then just print the total on chat cause it looks like it doesnt total the exp shared to players

**Comment by Travja** [comment]
You know, I think I found it. After a lot of digging, it appears that the party system is actually recursively calling the method to add exp over and over, getting smaller each time until it finally hits zero and terminates. If it hits zero before the server crashes, things should recover, but otherwise it'll drop the server. Now I can go about addressing this :P

**Comment by Travja** [comment]
Update on this since it's been a while... I'm actually not entirely sure what's going on. It doesn't appear to actually be calling it recursively. There are breaking cases. And in setting up sort of a simulated situation outside of a server context, it appears to operate fine. So I'm not sure what's exactly going on at the moment. I'll have to do some more digging with a second account on an actual server.

**Comment by Travja** [comment]
We can go ahead and re-open this when we get more information or when the time comes, but I'm just closing this out to clean things up a little.
